// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var door = {
  key: 17607508,
  loop: 0
};

var card = {
  key: 15065270,
  loop: 0
};

function getLoopCount(key) {
  var value = 1;
  var loops = 0;
  while(value !== key) {
    value = Math.imul(value, 7) % 20201227;
    loops = loops + 1 | 0;
  };
  return loops;
}

function transform(subj, loop) {
  var value = 1.0;
  var subj$1 = subj;
  for(var _for = 0; _for < loop; ++_for){
    value = value * subj$1 % 20201227.0;
  }
  return value | 0;
}

door.loop = getLoopCount(door.key);

card.loop = getLoopCount(card.key);

Pervasives.print_int(transform(door.key, card.loop));

Pervasives.print_newline(undefined);

exports.door = door;
exports.card = card;
exports.getLoopCount = getLoopCount;
exports.transform = transform;
/*  Not a pure module */
