name:                day8
version:             0.1.0.0
copyright:           "2020 Larqqa"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day8-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day8

tests:
  day8-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day8
